// eslint-disable-next-line n/no-unpublished-import
import { fn } from '@storybook/test';
import { ArcDto } from '#api/productStrategy';
import * as actual from './useStoryArcs';

export const useStoryArcs = fn(actual.useStoryArcs).mockName('useStoryArcs');

/**
 * Mock data for story arcs in the roadmap overview.
 */
export const mockStoryArcs: ArcDto[] = [
  {
    id: 'arc-1',
    workspace_id: 'workspace-1',
    name: 'AI-First Product Management',
    description: 'Helping Sarah achieve flow by fighting Context Switching',
    outcome_ids: ['outcome-1'],
    hero_ids: ['hero-1'],
    villain_ids: ['villain-1', 'villain-2'],
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
    heroes: [{
      id: 'hero-1',
      name: 'Sarah, The Solo Builder',
      identifier: 'HERO-1',
      description: 'A solo developer building products',
      is_primary: true,
    }],
    villains: [
      {
        id: 'villain-1',
        name: 'Context Switching',
        identifier: 'VILLAIN-1',
        description: 'The constant interruption of switching between tasks',
        villain_type: 'WORKFLOW',
        severity: 4,
        is_defeated: false,
      },
      {
        id: 'villain-2',
        name: 'AI Ignorance',
        identifier: 'VILLAIN-2',
        description: 'Lack of knowledge about AI tools',
        villain_type: 'INTERNAL',
        severity: 3,
        is_defeated: false,
      },
    ],
    status: 'in_progress',
    progress_percentage: 60,
    scenes_completed: 12,
    scenes_total: 28,
    started_quarter: 'Q1 2024',
    expected_quarter: 'Q2 2024',
  },
  {
    id: 'arc-2',
    workspace_id: 'workspace-1',
    name: 'Performance Optimization',
    description: 'Improving speed for power users by fighting Slowness',
    outcome_ids: ['outcome-2'],
    hero_ids: ['hero-2'],
    villain_ids: ['villain-3'],
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
    heroes: [{
      id: 'hero-2',
      name: 'Power User',
      identifier: 'HERO-2',
      description: 'An advanced user who needs performance',
      is_primary: false,
    }],
    villains: [{
      id: 'villain-3',
      name: 'Slow Response Times',
      identifier: 'VILLAIN-3',
      description: 'Application performance issues',
      villain_type: 'TECHNICAL',
      severity: 5,
      is_defeated: true,
    }],
    status: 'complete',
    progress_percentage: 100,
    scenes_completed: 18,
    scenes_total: 18,
    started_quarter: 'Q1 2024',
    expected_quarter: 'Q2 2024',
  },
  {
    id: 'arc-3',
    workspace_id: 'workspace-1',
    name: 'Onboarding Experience Redesign',
    description: 'Helping new users succeed by fighting Confusion',
    outcome_ids: ['outcome-3'],
    hero_ids: ['hero-3'],
    villain_ids: ['villain-4'],
    created_at: '2024-04-01T00:00:00Z',
    updated_at: '2024-04-01T00:00:00Z',
    heroes: [{
      id: 'hero-3',
      name: 'New User',
      identifier: 'HERO-3',
      description: 'A first-time user of the product',
      is_primary: false,
    }],
    villains: [{
      id: 'villain-4',
      name: 'Unclear First Steps',
      identifier: 'VILLAIN-4',
      description: 'Poor onboarding experience',
      villain_type: 'WORKFLOW',
      severity: 3,
      is_defeated: false,
    }],
    status: 'planned',
    progress_percentage: 0,
    scenes_completed: 0,
    scenes_total: 20,
    started_quarter: 'Q2 2024',
    expected_quarter: 'Q3 2024',
  },
  {
    id: 'arc-4',
    workspace_id: 'workspace-1',
    name: 'Mobile App Launch',
    description: 'Helping power users stay productive on-the-go by fighting Limited Access',
    outcome_ids: ['outcome-4'],
    hero_ids: ['hero-2'],
    villain_ids: ['villain-5', 'villain-6'],
    created_at: '2024-10-01T00:00:00Z',
    updated_at: '2024-10-01T00:00:00Z',
    heroes: [{
      id: 'hero-2',
      name: 'Power User',
      identifier: 'HERO-2',
      description: 'An advanced user who needs performance',
      is_primary: false,
    }],
    villains: [
      {
        id: 'villain-5',
        name: 'Limited Access',
        identifier: 'VILLAIN-5',
        description: 'Inability to access the app on mobile',
        villain_type: 'TECHNICAL',
        severity: 4,
        is_defeated: false,
      },
      {
        id: 'villain-6',
        name: 'Platform Constraints',
        identifier: 'VILLAIN-6',
        description: 'Mobile platform limitations',
        villain_type: 'EXTERNAL',
        severity: 3,
        is_defeated: false,
      },
    ],
    status: 'planned',
    progress_percentage: 0,
    scenes_completed: 0,
    scenes_total: 24,
    started_quarter: 'Q4 2024',
    expected_quarter: 'Q1 2025',
  },
];


