"""user api keys

Revision ID: 33de8a75753d
Revises: add_has_pending_job_field
Create Date: 2025-03-25 15:38:45.795939

"""
from textwrap import dedent
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

from src.config import settings

# revision identifiers, used by Alembic.
revision: str = '33de8a75753d'
down_revision: Union[str, None] = 'add_has_pending_job_field'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_key',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('provider', sa.Enum('OPENAI', name='apiprovider', schema='dev'), nullable=False),
        sa.Column('redacted_key', sa.String(), nullable=False),
        sa.Column('is_valid', sa.Boolean(), nullable=False),
        sa.Column('last_validated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['private.users.id'], ondelete='cascade'),
        sa.PrimaryKeyConstraint('id'),
        schema='dev'
    )
    op.create_index(op.f('ix_dev_user_key_id'), 'user_key', ['id'], unique=False, schema='dev')
    op.create_index(op.f('ix_dev_user_key_user_id'), 'user_key', ['user_id'], unique=False, schema='dev')

    op.execute(
        dedent(
            f"""
            ALTER TABLE dev.user_key ENABLE ROW LEVEL SECURITY;
            
            CREATE POLICY user_key_policy ON dev.user_key
                USING (user_id = dev.get_user_id_from_jwt())
                WITH CHECK (user_id = dev.get_user_id_from_jwt()); 

            GRANT SELECT, UPDATE, DELETE, INSERT ON TABLE dev.user_key TO {settings.postgrest_authenticated_role};
            """
        )
    )
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dev_user_key_user_id'), table_name='user_key', schema='dev')
    op.drop_index(op.f('ix_dev_user_key_id'), table_name='user_key', schema='dev')
    op.drop_table('user_key', schema='dev')
    # ### end Alembic commands ###
