"""github installation constraint

Revision ID: 4ad1dd0bfa19
Revises: 96a1df25e9a2
Create Date: 2025-09-20 10:08:52.857858

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4ad1dd0bfa19"
down_revision: Union[str, None] = "96a1df25e9a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_github_installation_installation_id",
        "github_installation",
        ["installation_id"],
        schema="private",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_github_installation_installation_id",
        "github_installation",
        schema="private",
        type_="unique",
    )
    # ### end Alembic commands ###
