"""github installation

Revision ID: 948197b7436e
Revises: c77ee45fc227
Create Date: 2025-02-27 19:05:25.933487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = "948197b7436e"
down_revision: Union[str, None] = "c77ee45fc227"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "github_installation",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("installation_id", sa.String(), nullable=False),
        sa.Column(
            "user_id", sa.UUID(), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["private.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="private",
    )
    op.create_index(
        op.f("ix_dev_github_installation_user_id"),
        "github_installation",
        ["user_id"],
        unique=False,
        schema="private",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_dev_github_installation_user_id"),
        table_name="github_installation",
        schema="dev",
    )
    op.drop_table("github_installation", schema="dev")
    # ### end Alembic commands ###
