"""user display preferences

Revision ID: c77ee45fc227
Revises: 40c8f769b104
Create Date: 2025-02-19 09:34:48.949617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c77ee45fc227'
down_revision: Union[str, None] = '40c8f769b104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True), schema='private')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_preferences', schema='private')
    # ### end Alembic commands ###
