"""Make a load of fields nullable

Revision ID: ca15162f6201
Revises: 96cab130ff77
Create Date: 2025-01-27 18:16:37.582476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ca15162f6201'
down_revision: Union[str, None] = '96cab130ff77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('initiative', 'type', schema='dev', existing_type=sa.Enum('FEATURE','BUGFIX','RESEARCH','CHORE', name='initiativetype', schema='dev'), nullable=True)
    op.alter_column('initiative', 'description', schema='dev', existing_type=sa.String(), nullable=True)

    op.alter_column('task', 'type', schema='dev', existing_type=sa.Enum('CODING','TESTING','DOCUMENTATION','DESIGN', name='tasktype', schema='dev'), nullable=True)
    op.alter_column('task', 'description', schema='dev', existing_type=sa.String(), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('initiative', 'type', schema='dev', existing_type=sa.Enum('FEATURE','BUGFIX','RESEARCH','CHORE', name='initiativetype', schema='dev'), nullable=False)
    op.alter_column('initiative', 'description', schema='dev', existing_type=sa.String(), nullable=False)

    op.alter_column('task', 'type', schema='dev', existing_type=sa.Enum('CODING','TESTING','DOCUMENTATION','DESIGN', name='tasktype', schema='dev'), nullable=False)
    op.alter_column('task', 'description', schema='dev', existing_type=sa.String(), nullable=False)

    # ### end Alembic commands ###
