"""TO_DO default status

Revision ID: f56f2a0d49b4
Revises: ca15162f6201
Create Date: 2025-02-15 10:38:06.960257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f56f2a0d49b4'
down_revision: Union[str, None] = 'ca15162f6201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status', server_default=sa.text("'TO_DO'"), nullable=False, schema='dev')
    op.alter_column('initiative', 'status', server_default=sa.text("'TO_DO'"), nullable=False, schema='dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status', server_default=None, nullable=True, schema='dev')
    op.alter_column('initiative', 'status', server_default=None, nullable=True, schema='dev')
    # ### end Alembic commands ###
