name: PR Hygiene
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check PR title (Conventional Commits)
        uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            test
            chore
      - name: Require basic checklist ticks
        uses: actions-ecosystem/action-regex-match@v2
        id: body
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '[\s\S]*- \[x\] PR title follows[\s\S]*- \[x\] [\s\S]*conventions[\s\S]*- \[x\] [\s\S]*Tests added/updated[\s\S]*'
      - name: Fail if checklist not satisfied
        if: steps.body.outputs.match == ''
        run: |
          echo "::error::Please complete the required checklist items in the PR body."
          exit 1
